### PR TITLE
make it faster

### PR DESCRIPTION
**Pull request by Mark2Mark**

### CODE REVIEW

**Comment by schriftgestalt** [comment]
Did you measure this. This shouldn’t be needed when you don’t set any values.

**Comment by Mark2Mark** [comment]
No need for measuring. Just used my eyes. Without it takes about 30 seconds on a basic latin charset font with 8 masters. It prints every single line into the macro panel like print ... print ... print ...

with it, it takes half a second.

M1 Mac, Glyphs 3.2

**Comment by Mark2Mark** [comment]
and what do you mean with "don’t set any values"? There’s nothing to set, afaik, at least not per UI.

**Comment by Mark2Mark** [comment]
Why is it so hard to just accept these 2 lines? They don’t hurt anyone and bring incredible performance boost. Look here:

**Before:**
https://user-images.githubusercontent.com/5824595/223739328-2597b737-9c5a-4e64-a8fc-c663e842a070.mov

**After (aka with disabling update interface):**
https://user-images.githubusercontent.com/5824595/223739499-311a95d7-e322-4f5e-916e-31d1349ff1e4.mov

**Comment by Mark2Mark** [comment]
Thanks  😄 

Just for the record: having color filters (smart lists) can cause the lagging (w/o disabling update interface), as Georg explained.

**Pull request merged**
