### PR TITLE
fix: whitespace error on circular glyph script

### PR DESCRIPTION
**Pull request by jpt**
There was a whitespace error breaking the `Build Circled Glyphs` script, this PR fixes it

### CODE REVIEW

**Comment by jpt** [comment]
Hmm, looks like this script may have more issues in Glyphs 3 actually. Let me see if I can get those too

**Comment by jpt** [comment]
It's getting as far as creating the the `_part`s, but fails with:

```

⚠️ Script Error:

Traceback (most recent call last):
  File "Build Circled Glyphs.py", line 691, in BuildCircledGlyphsMain
  File "GlyphsApp/__init__.py", line 459, in GSProxyShapes__getitem__
IndexError: list index out of range


Build Circled Glyphs Error: list index out of range
Traceback (most recent call last):
  File "Build Circled Glyphs.py", line 781, in BuildCircledGlyphsMain
  File "Build Circled Glyphs.py", line 691, in BuildCircledGlyphsMain
  File "GlyphsApp/__init__.py", line 459, in GSProxyShapes__getitem__
IndexError: list index out of range

```

**Comment by schriftgestalt** [comment]
it is 
```
print(Font.stems[0].horizontal)
print(Font.masters[0].stems)
```
So the font has a list of stem settings and each master has a value for it.

**Comment by jpt** [comment]
@schriftgestalt got it. there is probably a more elegant/pythonic way of doing this, but this does the trick

```
hstems = []	
vstems = []
for i, masterStem in enumerate(thisLayer.associatedFontMaster().stems):
	horizontal = False
	for stem in thisFont.stems:
		if(thisLayer.associatedFontMaster().stems[stem.horizontal] == i):
			horizontal = True
	if horizontal == True:
		hstems.append(masterStem)
	else:
		vstems.append(masterStem)
```

there were a few other errors with maybe python 3 related things, like not being able to iterate with `[1:]` style slices (`TypeError: '<' not supported between instances of 'slice' and 'int'`)

again, perhaps my solutions are not perfectly pythonic, but everything should be fixed as of 2527124

let me know if this causes any trouble for Glyphs 2

otherwise it should be safe to merge. thanks for the help!

**Comment by jpt** [comment]
This does not work on the black-background circles. Not sure why

**Comment by jpt** [comment]
Nevermind, got it!

Let me know how it goes 🙏

**Comment by jpt** [comment]
It looks like it's removing overlaps on the black circles for some reason; not sure if that was an old problem or is new as a result of this work

**Comment by jpt** [comment]
oh, no, at some point the hstems and vstems stopped working. I will take another look shortly.

**Pull request merged**
