### PR TITLE
Update Rebuild Components.py

### PR DESCRIPTION
**Pull request by weiweihuanghuang**
Detect .cap and .asc accents

### CODE REVIEW

**Comment by mekkablue** [comment]
I am not sure this should be part of the script. .cap is non-standard, and I don't understand the sense of .asc.

**Comment by weiweihuanghuang** [comment]
Ok, it's just someone asked me for this and I have also needed to use this, .asc is for diacritics on ascender glyphs, they're not always same as caps...

**Comment by davelab6** [comment]
If the community is using them maybe they should become standard

**Comment by schriftgestalt** [comment]
.cap suffixes are recognised by Glyphs.

**Comment by mekkablue** [comment]
Will have to add .case at one point, too.

**Pull request merged**
